/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AlunosStudentIdRouteImport } from './routes/alunos.$studentId'
import { Route as RegistrosIndexRouteImport } from './routes/registros.index'
import { Route as RegistrosNovoRouteImport } from './routes/registros.novo'
import { Route as TurmasIndexRouteImport } from './routes/turmas.index'
import { Route as TurmasClassIdRouteImport } from './routes/turmas.$classId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosStudentIdRoute = AlunosStudentIdRouteImport.update({
  id: '/alunos/$studentId',
  path: '/alunos/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrosIndexRoute = RegistrosIndexRouteImport.update({
  id: '/registros/',
  path: '/registros/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrosNovoRoute = RegistrosNovoRouteImport.update({
  id: '/registros/novo',
  path: '/registros/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const TurmasIndexRoute = TurmasIndexRouteImport.update({
  id: '/turmas/',
  path: '/turmas/',
  getParentRoute: () => rootRouteImport,
} as any)
const TurmasClassIdRoute = TurmasClassIdRouteImport.update({
  id: '/turmas/$classId',
  path: '/turmas/$classId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/alunos/$studentId': typeof AlunosStudentIdRoute
  '/registros/novo': typeof RegistrosNovoRoute
  '/turmas/$classId': typeof TurmasClassIdRoute
  '/registros/': typeof RegistrosIndexRoute
  '/turmas/': typeof TurmasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/alunos/$studentId': typeof AlunosStudentIdRoute
  '/registros/novo': typeof RegistrosNovoRoute
  '/turmas/$classId': typeof TurmasClassIdRoute
  '/registros': typeof RegistrosIndexRoute
  '/turmas': typeof TurmasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/alunos/$studentId': typeof AlunosStudentIdRoute
  '/registros/novo': typeof RegistrosNovoRoute
  '/turmas/$classId': typeof TurmasClassIdRoute
  '/registros/': typeof RegistrosIndexRoute
  '/turmas/': typeof TurmasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/redefinir-senha'
    | '/alunos/$studentId'
    | '/registros/novo'
    | '/turmas/$classId'
    | '/registros/'
    | '/turmas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/redefinir-senha'
    | '/alunos/$studentId'
    | '/registros/novo'
    | '/turmas/$classId'
    | '/registros'
    | '/turmas'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/redefinir-senha'
    | '/alunos/$studentId'
    | '/registros/novo'
    | '/turmas/$classId'
    | '/registros/'
    | '/turmas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  AlunosStudentIdRoute: typeof AlunosStudentIdRoute
  RegistrosNovoRoute: typeof RegistrosNovoRoute
  TurmasClassIdRoute: typeof TurmasClassIdRoute
  RegistrosIndexRoute: typeof RegistrosIndexRoute
  TurmasIndexRoute: typeof TurmasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos/$studentId': {
      id: '/alunos/$studentId'
      path: '/alunos/$studentId'
      fullPath: '/alunos/$studentId'
      preLoaderRoute: typeof AlunosStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registros/': {
      id: '/registros/'
      path: '/registros'
      fullPath: '/registros/'
      preLoaderRoute: typeof RegistrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registros/novo': {
      id: '/registros/novo'
      path: '/registros/novo'
      fullPath: '/registros/novo'
      preLoaderRoute: typeof RegistrosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turmas/': {
      id: '/turmas/'
      path: '/turmas'
      fullPath: '/turmas/'
      preLoaderRoute: typeof TurmasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turmas/$classId': {
      id: '/turmas/$classId'
      path: '/turmas/$classId'
      fullPath: '/turmas/$classId'
      preLoaderRoute: typeof TurmasClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  AlunosStudentIdRoute: AlunosStudentIdRoute,
  RegistrosNovoRoute: RegistrosNovoRoute,
  TurmasClassIdRoute: TurmasClassIdRoute,
  RegistrosIndexRoute: RegistrosIndexRoute,
  TurmasIndexRoute: TurmasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
